import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { supabase } from '@/lib/supabase';
import { Participant } from '@/types'; // Assuming Participant type aligns with supabase.ts Row

interface ParticipantFormProps {
  eventId: string;
  participant?: Participant | null; // For editing
  onSave: (participant: Participant) => void;
  onCancel: () => void;
}

const ParticipantForm: React.FC<ParticipantFormProps> = ({ eventId, participant, onSave, onCancel }) => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [identifier, setIdentifier] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (participant) {
      setName(participant.name);
      setEmail(participant.email);
      setIdentifier(participant.identifier); // Identifier is required
    } else {
      setName('');
      setEmail('');
      setIdentifier('');
    }
  }, [participant]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    if (!name || !email || !identifier) {
      setError('Name, Email, and Identifier are required.');
      setLoading(false);
      return;
    }

    try {
      console.log('event: ', participant, eventId);
      
      let savedParticipant;
      const participantData = {
        name,
        email,
        identifier,
        event_id: eventId,
      };

      if (participant?.id) {
        // Update existing participant
        const { data, error: updateError } = await supabase
          .from('participants')
          .update(participantData)
          .eq('id', participant.id)
          .select()
          .single();
        if (updateError) throw updateError;
        savedParticipant = data;
      } else {
        // Create new participant
        // qr_token will likely be generated by a DB trigger or function
        const { data, error: insertError } = await supabase
          .from('participants')
          .insert({ ...participantData, qr_usage_count: 0, is_revoked: false })
          .select()
          .single();
        if (insertError) throw insertError;
        savedParticipant = data;
      }
      
      if (savedParticipant) {
        onSave(savedParticipant as Participant);
      } else {
        throw new Error('Failed to save participant.');
      }

    } catch (err) {
      console.error('Error saving participant:', err);
      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError('An unexpected error occurred.');
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {error && <p className="text-sm text-destructive">{error}</p>}
      <div>
        <Label htmlFor="name">Name</Label>
        <Input 
          id="name" 
          value={name} 
          onChange={(e) => setName(e.target.value)} 
          placeholder="John Doe"
          required 
        />
      </div>
      <div>
        <Label htmlFor="email">Email</Label>
        <Input 
          id="email" 
          type="email" 
          value={email} 
          onChange={(e) => setEmail(e.target.value)} 
          placeholder="john.doe@example.com"
          required 
        />
      </div>
      <div>
        <Label htmlFor="identifier">Identifier</Label>
        <Input 
          id="identifier" 
          value={identifier} 
          onChange={(e) => setIdentifier(e.target.value)} 
          placeholder="e.g., Employee ID, Ticket Number"
          required
        />
      </div>
      <div className="flex justify-end gap-2 pt-2">
        <Button type="button" variant="outline" onClick={onCancel} disabled={loading}>
          Cancel
        </Button>
        <Button type="submit" disabled={loading}>
          {loading ? (participant?.id ? 'Saving...' : 'Adding...') : (participant?.id ? 'Save Changes' : 'Add Participant')}
        </Button>
      </div>
    </form>
  );
};

export default ParticipantForm;
